[package]
name = "pomo"
version = "0.1.0"
edition = "2021"
authors = ["Peter A. Ramaldes <peter.ramaldes@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.2", features = ["derive"] }
